version: "3"
services:
    redis:
        container_name: dc-redis
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ./data:/data
    redis-commander:
        command: --redis-host redis
        container_name: dc-redis-commander
        image: tenstartups/redis-commander
        links:
            - redis:dc-redis
        ports:
            - "8082:8081"
